apiVersion: apps/v1
kind: Deployment
metadata:
  name: wagworld-store
  namespace: default
spec:
  selector:
    matchLabels:
      app: wagworld-store
  replicas: 1 
  template: 
    metadata:
      labels:
        app: wagworld-store
    spec:
      containers:
      - name: wagworld-store
        image: nomanakram29/wagworld-store
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wagworld-store
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: wagworld-store
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
